# Generated by Django 2.1.5 on 2023-03-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('releaseDate', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Movie'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
