# Generated by Django 2.1.5 on 2023-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20230321_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default='Anonymous User', max_length=128),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=2),
        ),
    ]
