# Generated by Django 2.2.28 on 2023-03-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20230323_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name_plural': 'Shows'},
        ),
    ]
