# Generated by Django 2.2.28 on 2023-03-24 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20230324_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
