# Generated by Django 2.2.28 on 2023-03-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_movie_avgrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avgRating',
        ),
    ]
