# Generated by Django 2.2.28 on 2023-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0017_remove_movie_avgrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avgRating',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
