# Generated by Django 2.2.28 on 2023-03-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_movie_avgrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='avgRating',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avgRating',
            field=models.FloatField(default=-1),
        ),
    ]
