# Generated by Django 2.2.28 on 2023-03-24 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0020_auto_20230324_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvrating',
            name='user',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
